# Generated by Django 3.2.13 on 2022-05-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='book_time',
            field=models.CharField(blank=True, choices=[('17:30', '17:30'), ('17:45', '17:45'), ('18:00', '18:00'), ('18:15', '18:15')], max_length=5),
        ),
        migrations.DeleteModel(
            name='Time',
        ),
    ]
