# Generated by Django 3.2.13 on 2022-05-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='book_time',
            field=models.CharField(choices=[('17:30', '17:30'), ('17:45', '17:45')], default='17:30', max_length=5),
            preserve_default=False,
        ),
    ]
