# Generated by Django 3.2.13 on 2022-05-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default=True, max_length=25, unique=True),
            preserve_default=False,
        ),
    ]
