# Generated by Django 3.2.13 on 2022-05-09 10:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0003_siteusers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiteUsers',
            new_name='SiteUser',
        ),
    ]
