# Generated by Django 3.2.13 on 2022-05-17 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20220517_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='table_id',
        ),
    ]
