# Generated by Django 3.2.13 on 2022-05-23 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_remove_table_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='end_time',
            field=models.CharField(choices=[('21:15', '21:15'), ('19:30', '19:30'), ('21:45', '21:45'), ('00:00', '00:00'), ('20:45', '20:45'), ('23:15', '23:15'), ('22:45', '22:45'), ('20:30', '20:30'), ('22:15', '22:15'), ('23:00', '23:00'), ('22:00', '22:00'), ('22:30', '22:30'), ('21:30', '21:30'), ('20:00', '20:00'), ('20:15', '20:15'), ('21:00', '21:00'), ('19:45', '19:45'), ('23:30', '23:30'), ('23:45', '23:45')], default=True, max_length=5),
            preserve_default=False,
        ),
    ]
