# Generated by Django 3.2.13 on 2022-05-27 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_alter_reservation_book_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='book_time',
            field=models.IntegerField(choices=[(1050, '17:30'), (1065, '17:45'), (1080, '18:00'), (1095, '18:15'), (1110, '18:30'), (1125, '18:45'), (1140, '19:00'), (1155, '19:15'), (1170, '19:30'), (1185, '19:45'), (1200, '20:00'), (1215, '20:15'), (1230, '20:30'), (1245, '20:45'), (1260, '21:00'), (1275, '21:15'), (1290, '21:30'), (1305, '21:45'), (1320, '22:00')]),
        ),
    ]
